name: Rust tests (4.06)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [macos-latest, ubuntu-latest]
        ocaml-version: ["4.06.0"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.0.0
      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: avsm/setup-ocaml@v1.0
        with:
          ocaml-version: ${{ matrix.ocaml-version }}
      - name: Build
        run: cargo build --tests --features=link
      - name: Run Rust tests
        run: cargo test --features=link
